
# for flashing : press boot button for 2-3 seconds before the serial connection initialize
# After OTA update, the EN (reset) button must be pressed to run firmware
# do not use gpio12 (MTDI)


############## General configuration

substitutions:
  name: floor-heating-controller
  friendly_name: "Floor heating"
  revision: "1.106"
  
  #board and compilation
  board: nodemcu-32s
  framework: esp-idf #arduino
  
  #time
  TZ: "Europe/Zurich" #timezone
  reboot_days_of_week: "MON"
  reboot_hours: "5"
  reboot_minutes: "0"
  reboot_seconds: "0"
  # valve_maintenance_interval: "7days"
  onboot_valve_calibration_delay: "1min"
 
  
web_server:
  port: 80
  # log: false
  
# Enable Home Assistant API
api:
  reboot_timeout: 30min

  
############## Channels definition (packages as template : https://esphome.io/guides/configuration-types.html#packages-as-templates)
packages:

  channel_1: !include
    file: heating_channel.yaml
    vars:
      channel_number: 1
      id: wc
      frendly_name: wc
      temperature_sensor: corridor_temperature_sensor
      default_target_temperature_low: "19 °C" #ASHRAE studies recommend 21°C with a band of 2°C which result in 90% occupant acceptability
      default_target_temperature_high: "20 °C"
      visual_min_temperature: "10 °C"
      visual_max_temperature: "30 °C"
      visual_temperature_step: "0.1 °C"
      check_interval: "15min"
      bemf_trigger_initial_value: "0.105"
      ## do not change : 
      bemf_sensor_adc: BEMF_1_2_sensor_ADC
      bemf_linked_with_channel: 2
      sn74hc595_IA_pin: 0
      sn74hc595_IB_pin: 1
      
      

  channel_2: !include
    file: heating_channel.yaml
    vars:
      channel_number: 2
      id: storage
      frendly_name: storage
      temperature_sensor: reduit_temperature_sensor
      default_target_temperature_low: "19 °C"
      default_target_temperature_high: "20 °C"
      visual_min_temperature: "10 °C"
      visual_max_temperature: "30 °C"
      visual_temperature_step: "0.1 °C"
      check_interval: "16min"
      bemf_trigger_initial_value: "0.105"
      ## do not change : 
      bemf_sensor_adc: BEMF_1_2_sensor_ADC
      bemf_linked_with_channel: 1
      sn74hc595_IA_pin: 2
      sn74hc595_IB_pin: 3
      

      
  channel_3: !include
    file: heating_channel.yaml
    vars:
      channel_number: 3
      id: living
      frendly_name: living
      temperature_sensor: living_room_temperature_sensor
      default_target_temperature_low: "21 °C"
      default_target_temperature_high: "23 °C"
      visual_min_temperature: "10 °C"
      visual_max_temperature: "30 °C"
      visual_temperature_step: "0.1 °C"
      check_interval: "17min"
      bemf_trigger_initial_value: "0.105"
      ## do not change :
      bemf_sensor_adc: BEMF_3_4_sensor_ADC
      bemf_linked_with_channel: 4
      sn74hc595_IA_pin: 4
      sn74hc595_IB_pin: 5
      
      
  channel_4: !include
    file: heating_channel.yaml
    vars:
      channel_number: 4
      id: dining
      frendly_name: dining
      temperature_sensor: indoor_temperature_sensor
      default_target_temperature_low: "21 °C"
      default_target_temperature_high: "23 °C"
      visual_min_temperature: "10 °C"
      visual_max_temperature: "30 °C"
      visual_temperature_step: "0.1 °C"
      check_interval: "18min"  
      bemf_trigger_initial_value: "0.105"
      ## do not change :
      bemf_sensor_adc: BEMF_3_4_sensor_ADC
      bemf_linked_with_channel: 3
      sn74hc595_IA_pin: 6
      sn74hc595_IB_pin: 7
        
      
  channel_5: !include
    file: heating_channel.yaml
    vars:
      channel_number: 5
      id: kitchen
      frendly_name: kitchen
      temperature_sensor: living_room_temperature_sensor
      default_target_temperature_low: "21 °C"
      default_target_temperature_high: "23 °C"
      visual_min_temperature: "10 °C"
      visual_max_temperature: "30 °C"
      visual_temperature_step: "0.1 °C"
      check_interval: "15min"
      bemf_trigger_initial_value: "0.105"
      ## do not change :
      bemf_sensor_adc: BEMF_5_6_sensor_ADC
      bemf_linked_with_channel: 6
      sn74hc595_IA_pin: 8
      sn74hc595_IB_pin: 9
      
      
  channel_6: !include
    file: heating_channel.yaml
    vars:
      channel_number: 6
      id: office
      frendly_name: office
      temperature_sensor: office_temperature_sensor
      default_target_temperature_low: "20 °C"
      default_target_temperature_high: "21 °C"
      visual_min_temperature: "10 °C"
      visual_max_temperature: "30 °C"
      visual_temperature_step: "0.1 °C"
      check_interval: "16min"
      bemf_trigger_initial_value: "0.090"
      ## do not change :
      bemf_sensor_adc: BEMF_5_6_sensor_ADC
      bemf_linked_with_channel: 5
      sn74hc595_IA_pin: 10
      sn74hc595_IB_pin: 11
      
      
  channel_7: !include
    file: heating_channel.yaml
    vars:
      channel_number: 7
      id: bedroom
      frendly_name: bedroom
      temperature_sensor: bedroom_temperature_sensor
      default_target_temperature_low: "16 °C"
      default_target_temperature_high: "18 °C"
      visual_min_temperature: "10 °C"
      visual_max_temperature: "30 °C"
      visual_temperature_step: "0.1 °C"
      check_interval: "17min"
      bemf_trigger_initial_value: "0.105"
      ## do not change :
      bemf_sensor_adc: BEMF_7_8_sensor_ADC
      bemf_linked_with_channel: 8
      sn74hc595_IA_pin: 12
      sn74hc595_IB_pin: 13
         
      
  channel_8: !include
    file: heating_channel.yaml
    vars:
      channel_number: 8
      id: bathroom
      frendly_name: bathroom
      temperature_sensor: bathroom_temperature_sensor
      default_target_temperature_low: "22 °C"
      default_target_temperature_high: "24 °C"
      visual_min_temperature: "10 °C"
      visual_max_temperature: "30 °C"
      visual_temperature_step: "0.1 °C"
      check_interval: "18min"
      bemf_trigger_initial_value: "0.105"
      ## do not change :
      bemf_sensor_adc: BEMF_7_8_sensor_ADC
      bemf_linked_with_channel: 7
      sn74hc595_IA_pin: 14
      sn74hc595_IB_pin: 15
         


  wifi: !include wifi.yaml
  board: !include board.yaml
  time: !include time.yaml
  #climate: !include climate.yaml
  #script_termostat_check: !include script_termostat_check.yaml
  script_calibrate_valves: !include script_calibrate_valves.yaml
  #switch_gpio: !include switch_gpio.yaml
  switch_others: !include switch_others.yaml
  inputs: !include inputs.yaml
  #covers: !include covers.yaml
  #sensor_bemf: !include sensor_bemf.yaml #back electromotive force (back EMF)
  sensor_adc: !include sensor_adc.yaml
  sensor_temperature: !include sensor_temperature.yaml
  sensor_others: !include sensor_others.yaml
  


